server:
  port: 8090

spring:
  datasource:
    url: jdbc:mysql://localhost/user
    username: root
    password: 12345
  jpa:
    hibernate:
      ddl-auto: update
jwt:
  //secret: ${KEYSECRET_SECURITY:eyJhbGciOiJIUzI1NiJ9eyJzdWIiOigkcPWbYjPkq6aClfachNJwhRLjbbKZRQnDz72GtF8s}
  //expiration: ${EXPIRE_DAYS_SECURITY:43600000}
  secret: eyJhbGciOiJIUzI1NiJ9eyJzdWIiOigkcPWbYjPkq6aClfachNJwhRLjbbKZRQnDz72GtF8s
  expiration: 560000

management:
  endpoints:
    web:
      exposure:
        include: "*"